# Generated by Django 6.0 on 2026-01-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_subcatgory_delete_subcatgory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.FileField(upload_to='Assets/User/Photo/')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=8)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
