# Generated by Django 6.0 on 2026-01-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_id',
        ),
    ]
