# Generated by Django 6.0 on 2026-01-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_subcatgory_delete_subcatgory'),
        ('Guest', '0003_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deafuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deafuser_photo', models.FileField(upload_to='', verbose_name='Assets/DeafUser/Photo')),
                ('deafuser_name', models.CharField(max_length=30)),
                ('deafuser_email', models.CharField(max_length=30)),
                ('deafuser_address', models.CharField(max_length=30)),
                ('deafuser_password', models.CharField(max_length=8)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
