# Generated by Django 5.2.12 on 2026-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_deafuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deafuser',
            name='deafuser_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_deafuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
