# Generated by Django 5.2.13 on 2026-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_deafuser_deafuser_status_alter_tbl_deafuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deafuser',
            name='deafuser_contact',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
