# Generated by Django 5.2.13 on 2026-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_deafuser_deafuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_deafuser',
            name='deafuser_photo',
            field=models.FileField(upload_to='Assets/DeafUser/Photo'),
        ),
    ]
