# Generated by Django 5.2.13 on 2026-04-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_deafuser_deafuser_status_alter_tbl_deafuser_id_and_more'),
        ('User', '0011_tbl_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='deafuser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deafuser'),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
